Repository kreshuklab/plant-seg, pull requests merged in 2024-10, with the labels that each got.

#341 New export widget
  .gitignore
  docs/snippets/napari/io/widget_export_stacks.py
  plantseg/core/image.py
  plantseg/headless/headless.py
  plantseg/tasks/io_tasks.py
  plantseg/viewer_napari/containers.py
  plantseg/viewer_napari/widgets/__init__.py
  plantseg/viewer_napari/widgets/dataprocessing.py
  plantseg/viewer_napari/widgets/io.py
  plantseg/viewer_napari/widgets/prediction.py
  plantseg/viewer_napari/widgets/proofreading.py
  plantseg/viewer_napari/widgets/segmentation.py
  plantseg/viewer_napari/widgets/utils.py
  tests/functionals/prediction/test_size_finder.py
  tests/headless/test_headless.py
  tests/tasks/test_io_tasks.py
Labels: enhancement, GUI

#343 Fix voxel size unit
  plantseg/core/__init__.py
  plantseg/core/image.py
  plantseg/functionals/dataprocessing/advanced_dataprocessing.py
  plantseg/functionals/prediction/prediction.py
  plantseg/io/__init__.py
  plantseg/io/h5.py
  plantseg/io/io.py
  plantseg/io/tiff.py
  plantseg/io/voxelsize.py
  plantseg/io/zarr.py
  plantseg/tasks/dataprocessing_tasks.py
  plantseg/viewer_napari/widgets/dataprocessing.py
  tests/core/test_image.py
  tests/core/test_voxelsize.py
  tests/functionals/dataprocessing/test_labelprocessing.py
  tests/headless/test_headless.py
  tests/io/test_io.py
  tests/tasks/test_io_tasks.py
  tests/tasks/test_prediction_tasks.py
  tests/tasks/test_segmentation_tasks.py
  tests/widgets/test_widget_open_file.py
  tests/widgets/test_widget_preprocessing.py
Labels: bug

#348 Match conda recipe and include `package_data` logo
  .github/workflows/build-and-test-package.yml
  conda-recipe/meta.yaml
  docs/chapters/getting_started/installation.md
  environment-elife.yml
  environment.yaml
  setup.py
Labels: bug, GUI
