Repository kreshuklab/plant-seg, pull requests merged in 2024-09, with the labels that each got.

#304 fix(widget-IO): temp fix #282 and auto generate layer name
  plantseg/viewer_napari/widgets/io.py
Labels: bug, enhancement, GUI

#307 Compute best patch and halo shapes by default, reduce user effort
  plantseg/core/zoo.py
  plantseg/functionals/predictions/predictions.py
  plantseg/functionals/predictions/utils/array_predictor.py
  plantseg/functionals/predictions/utils/size_finder.py
  plantseg/tasks/predictions_tasks.py
  plantseg/viewer_napari/widgets/io.py
  plantseg/viewer_napari/widgets/predictions.py
  tests/core/test_zoo.py
  tests/functionals/predictions/test_heuristics.py
  tests/functionals/predictions/test_size_finder.py
Labels: bug, enhancement, GUI

#310 Make VoxelSize iterable and array-like, remove `.is_valid`
  plantseg/core/image.py
  plantseg/core/voxelsize.py
  plantseg/viewer_napari/widgets/io.py
  tests/core/test_image.py
  tests/core/test_voxelsize.py
  tests/io/test_io.py
Labels: enhancement

#311 refactor: use `magicgui.types.Separator`
  plantseg/viewer_napari/widgets/predictions.py
Labels: enhancement, GUI

#312 Fix TIFF default layer name and hide key widget
  plantseg/viewer_napari/widgets/io.py
Labels: bug, GUI

#313 Fix size finder and widgets for 2D UNet
  plantseg/core/zoo.py
  plantseg/functionals/predictions/predictions.py
  plantseg/functionals/predictions/utils/size_finder.py
  plantseg/viewer_napari/widgets/predictions.py
  tests/functionals/predictions/test_size_finder.py
Labels: bug, enhancement, GUI

#317 Group widgets for batch `.hide()`/`.show()`
  plantseg/functionals/dataprocessing/dataprocessing.py
  plantseg/viewer_napari/widgets/dataprocessing.py
  plantseg/viewer_napari/widgets/io.py
  plantseg/viewer_napari/widgets/predictions.py
  plantseg/viewer_napari/widgets/segmentation.py
Labels: enhancement, GUI

#318 Fix and document distance transform watershed for 2D pmaps/images
  docs/chapters/python_api/cnn_predictions.md
  evaluation/README.md
  plantseg/core/image.py
  plantseg/functionals/prediction/__init__.py
  plantseg/functionals/prediction/prediction.py
  plantseg/functionals/prediction/utils/__init__.py
  plantseg/functionals/prediction/utils/array_dataset.py
  plantseg/functionals/prediction/utils/array_predictor.py
  plantseg/functionals/prediction/utils/size_finder.py
  plantseg/functionals/prediction/utils/slice_builder.py
  plantseg/functionals/prediction/utils/utils.py
  plantseg/functionals/predictions/__init__.py
  plantseg/functionals/segmentation/segmentation.py
  plantseg/io/h5.py
  plantseg/io/zarr.py
  plantseg/tasks/prediction_tasks.py
  plantseg/tasks/segmentation_tasks.py
  plantseg/training/h5dataset.py
  plantseg/viewer_napari/containers.py
  plantseg/viewer_napari/widgets/__init__.py
  plantseg/viewer_napari/widgets/dataprocessing.py
  plantseg/viewer_napari/widgets/prediction.py
  plantseg/viewer_napari/widgets/segmentation.py
  tests/conftest.py
  tests/functionals/predictions/test_size_finder.py
  tests/functionals/segmentation/test_segmentation.py
  tests/tasks/test_prediction_tasks.py
  tests/tasks/test_segmentation_tasks.py
Labels: bug, enhancement, GUI

#320 PlantSeg v2 docs base
  .github/workflows/build-deploy-book.yml
  docs/chapters/plantseg_classic_cli/index.md
  docs/chapters/plantseg_classic_gui/cnn_prediction.md
  docs/chapters/plantseg_classic_gui/data_processing.md
  docs/chapters/plantseg_classic_gui/index.md
  docs/chapters/plantseg_classic_gui/segmentation.md
  docs/chapters/plantseg_interactive_napari/data_processing.md
  docs/chapters/plantseg_interactive_napari/headless_batch_processing.md
  docs/chapters/plantseg_interactive_napari/import_export.md
  docs/chapters/plantseg_interactive_napari/proofreading.md
  docs/chapters/plantseg_models/custom_datasets.md
  docs/chapters/python_api/cnn_prediction.md
  docs/chapters/python_api/cnn_predictions.md
  docs/chapters/python_api/data_processing.md
  docs/chapters/python_api/io.md
  docs/chapters/python_api/segmentation.md
  docs/index.md
  docs/snippets/napari/dataprocessing/gaussian_smoothing.py
  docs/snippets/napari/dataprocessing/rescale.md
  mkdocs.yml
  tests/functionals/prediction/test_size_finder.py
Labels: documentation

#321 Recover and document over-/under-seg fix by nuclei
  plantseg/functionals/dataprocessing/advanced_dataprocessing.py
  plantseg/tasks/dataprocessing_tasks.py
  plantseg/viewer_napari/containers.py
  plantseg/viewer_napari/widgets/__init__.py
  plantseg/viewer_napari/widgets/dataprocessing.py
Labels: documentation, enhancement, GUI

#323 Add un-/re-do and save-/load-states for proofreading tool
  plantseg/core/image.py
  plantseg/viewer_napari/containers.py
  plantseg/viewer_napari/widgets/__init__.py
  plantseg/viewer_napari/widgets/proofreading.py
Labels: enhancement, GUI

#327 Record issue missing button
  .github/workflows/build-deploy-book.yml
  docs/chapters/getting_started/troubleshooting.md
  plantseg/legacy_gui/plantsegapp.py
Labels: documentation, Legacy

#328 Fix and integrate lifted multicut widget into agglomeration widget
  conda-recipe/meta.yaml
  plantseg/functionals/segmentation/segmentation.py
  plantseg/tasks/segmentation_tasks.py
  plantseg/viewer_napari/containers.py
  plantseg/viewer_napari/widgets/__init__.py
  plantseg/viewer_napari/widgets/prediction.py
  plantseg/viewer_napari/widgets/segmentation.py
Labels: enhancement, GUI

#330 Refactor and recover widgets: cropping and label processing
  plantseg/functionals/dataprocessing/labelprocessing.py
  plantseg/tasks/dataprocessing_tasks.py
  plantseg/viewer_napari/containers.py
  plantseg/viewer_napari/widgets/__init__.py
  plantseg/viewer_napari/widgets/dataprocessing.py
  tests/functionals/dataprocessing/test_labelprocessing.py
Labels: enhancement, GUI

#326 PlantSeg v2: Final polishment of GUI
  .pre-commit-config.yaml
  conda-recipe/meta.yaml
  docs/chapters/getting_started/troubleshooting.md
  environment-dev.yaml
  environment-elife.yml
  environment.yaml
  plantseg/functionals/dataprocessing/labelprocessing.py
  plantseg/functionals/segmentation/segmentation.py
  plantseg/tasks/dataprocessing_tasks.py
  plantseg/tasks/segmentation_tasks.py
  plantseg/viewer_napari/containers.py
  plantseg/viewer_napari/viewer.py
  plantseg/viewer_napari/widgets/__init__.py
  plantseg/viewer_napari/widgets/dataprocessing.py
  plantseg/viewer_napari/widgets/docs.py
  plantseg/viewer_napari/widgets/io.py
  plantseg/viewer_napari/widgets/prediction.py
  plantseg/viewer_napari/widgets/proofreading.py
  plantseg/viewer_napari/widgets/segmentation.py
  test.ipynb
  tests/functionals/dataprocessing/test_labelprocessing.py
Labels: bug, enhancement, GUI

#331 refactor(GUI): rename and reorder widgets for intuitive sequential flow
  plantseg/viewer_napari/containers.py
  plantseg/viewer_napari/viewer.py
  plantseg/viewer_napari/widgets/dataprocessing.py
  plantseg/viewer_napari/widgets/io.py
  plantseg/viewer_napari/widgets/prediction.py
  plantseg/viewer_napari/widgets/segmentation.py
Labels: enhancement, GUI

#335 fix h5 export
  plantseg/core/image.py
  plantseg/io/h5.py
  plantseg/io/zarr.py
  tests/io/test_io.py
  tests/tasks/test_io_tasks.py
Labels: bug

#336 fix: avoid reading logo file from docs folder
  plantseg/resources/logo_white.png
  plantseg/viewer_napari/widgets/docs.py
Labels: bug, GUI
