Repository kreshuklab/plant-seg, pull requests merged in 2024-05, with the labels that each got.

#229 Dev Env: Add BioImage.IO Core dependency and fix CUDA installation
  docs/chapters/getting_started/contributing.md
  environment-dev.yaml
Labels: bug, BioImage.IO

#227 Napari GUI: Fix voxel size precision, font size, and rearrange widgets
  plantseg/viewer/containers.py
  plantseg/viewer/viewer.py
  plantseg/viewer/widget/dataprocessing.py
  plantseg/viewer/widget/io.py
  plantseg/viewer/widget/predictions.py
  plantseg/viewer/widget/segmentation.py
Labels: bug, enhancement, GUI

#230 Documentation: Migrate to MkDocs; update installation, README, and logo
  .github/workflows/build-deploy-book.yml
  README.md
  docs/chapters/getting_started/contributing.md
  docs/chapters/getting_started/installation.md
  docs/chapters/getting_started/quick_start.md
  docs/chapters/plantseg_classic_cli/index.md
  docs/chapters/plantseg_interactive_napari/data_processing.md
  docs/chapters/plantseg_interactive_napari/extra_pred.md
  docs/chapters/plantseg_interactive_napari/extra_seg.md
  docs/chapters/plantseg_interactive_napari/headless_batch_processing.md
  docs/chapters/plantseg_interactive_napari/index.md
  docs/chapters/plantseg_interactive_napari/unet_gasp_workflow.md
  docs/chapters/plantseg_interactive_napari/unet_training.md
  docs/chapters/python_api/data_processing.md
  docs/chapters/python_api/index.md
  docs/index.md
  docs/logo_transparent.png
  docs/logo_white.png
  mkdocs.yml
Labels: documentation

#231 Type Fix: `np.array` is not a type, change to `np.ndarray`
  docs/chapters/python_api/cnn_predictions.md
  docs/chapters/python_api/segmentation.md
  plantseg/dataprocessing/dataprocessing.py
  plantseg/dataprocessing/functional/advanced_dataprocessing.py
  plantseg/dataprocessing/functional/dataprocessing.py
  plantseg/dataprocessing/functional/labelprocessing.py
  plantseg/io/h5.py
  plantseg/io/tiff.py
  plantseg/io/zarr.py
  plantseg/predictions/functional/predictions.py
  plantseg/segmentation/functional/segmentation.py
Labels: bug

#237 Fix Legacy GUI after v1.7.0
  plantseg/legacy_gui/gui_tools.py
  plantseg/pipeline/raw2seg.py
  plantseg/predictions/functional/array_predictor.py
  plantseg/predictions/predict.py
  plantseg/utils.py
Labels: bug, Legacy

#233 Fix `CYX`/`CZYX` pad/halo, fix `io.zarr`/tests, fix typing, refactor model load
  plantseg/dataprocessing/dataprocessing.py
  plantseg/dataprocessing/functional/dataprocessing.py
  plantseg/dataprocessing/functional/labelprocessing.py
  plantseg/io/h5.py
  plantseg/io/io.py
  plantseg/io/pil.py
  plantseg/io/tiff.py
  plantseg/io/zarr.py
  plantseg/models/zoo.py
  plantseg/predictions/functional/array_dataset.py
  plantseg/predictions/functional/predictions.py
  plantseg/predictions/functional/utils.py
  plantseg/predictions/predict.py
  plantseg/run_plantseg.py
  plantseg/segmentation/functional/segmentation.py
  plantseg/training/model.py
  plantseg/utils.py
  plantseg/viewer/headless.py
  plantseg/viewer/widget/dataprocessing.py
  plantseg/viewer/widget/predictions.py
  tests/conftest.py
  tests/test_data_processing.py
  tests/test_io_zarr.py
  tests/test_model.py
  tests/test_model_zoo.py
Labels: bug, enhancement

#239 Headless: Handle multi-channel prediction output and add docs
  docs/chapters/getting_started/installation.md
  docs/chapters/getting_started/troubleshooting.md
  docs/chapters/plantseg_interactive_napari/headless_batch_processing.md
  plantseg/viewer/headless.py
  plantseg/viewer/widget/predictions.py
  plantseg/viewer/widget/utils.py
Labels: documentation, enhancement

#240 Doc: Data/models, train/add new models, Jupyter Book remnant
  README.md
  docs/README.md
  docs/_config.yml
  docs/_toc.yml
  docs/chapters/getting_started/index.md
  docs/chapters/plantseg_models/index.md
  docs/chapters/plantseg_models/training.md
  docs/logos/logo.png
  docs/logos/logo_transparent.png
  docs/logos/logo_white.png
  docs/references.bib
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, GUI

#247 BioImage.IO Core: Execute PlantSeg-compatible models by nickname
  conda-recipe/meta.yaml
  environment-dev.yaml
  environment.yaml
  plantseg/models/__init__.py
  plantseg/models/zoo.py
  plantseg/predictions/functional/predictions.py
  plantseg/viewer/widget/predictions.py
  tests/test_bioimageio.py
Labels: enhancement, BioImage.IO, GUI

#249 API docs | Docs screenshots | Refactor rescaling | Rearrange widgets
  .github/workflows/build-deploy-book.yml
  README.md
  docs/chapters/getting_started/index.md
  docs/chapters/getting_started/installation.md
  docs/chapters/plantseg_interactive_napari/data_processing.md
  docs/chapters/plantseg_interactive_napari/extra.md
  docs/chapters/plantseg_interactive_napari/extra_pred.md
  docs/chapters/plantseg_interactive_napari/import_export.md
  docs/chapters/plantseg_interactive_napari/proofreading.md
  docs/chapters/plantseg_interactive_napari/unet_gasp_workflow.md
  docs/chapters/plantseg_models/custom_datasets.md
  docs/chapters/python_api/cnn_predictions.md
  docs/chapters/python_api/data_processing.md
  docs/chapters/python_api/io.md
  docs/chapters/python_api/segmentation.md
  docs/index.md
  docs/snippets/__init__.py
  docs/snippets/napari/dataprocessing/gaussian_smoothing.py
  docs/snippets/napari/dataprocessing/rescale.md
  docs/snippets/napari_widgets_render.py
  mkdocs.yml
  plantseg/dataprocessing/functional/dataprocessing.py
  plantseg/dataprocessing/functional/labelprocessing.py
  plantseg/io/h5.py
  plantseg/io/io.py
  plantseg/io/tiff.py
  plantseg/io/zarr.py
  plantseg/predictions/functional/predictions.py
  plantseg/segmentation/functional/segmentation.py
  plantseg/viewer/containers.py
  plantseg/viewer/viewer.py
  plantseg/viewer/widget/dataprocessing.py
  plantseg/viewer/widget/extra_widgets.py
  plantseg/viewer/widget/io.py
  plantseg/viewer/widget/predictions.py
  plantseg/viewer/widget/segmentation.py
  plantseg/viewer/widget/utils.py
Labels: documentation, enhancement, GUI

#256 Improve use of `Enum` as widget choices and fix types
  plantseg/segmentation/functional/segmentation.py
  plantseg/viewer/widget/dataprocessing.py
  plantseg/viewer/widget/segmentation.py
Labels: bug, enhancement
