Repository kreshuklab/plant-seg, pull requests merged in 2025-01, with the labels that each got.

#382 Fix `anaconda_telemetry` error in CI
  .github/workflows/build-and-publish-docs.yml
  .github/workflows/build-and-test-package.yml
Labels: bug

#381 Add tests for and fix nuclei-assisted post-processing
  plantseg/functionals/dataprocessing/advanced_dataprocessing.py
  plantseg/tasks/dataprocessing_tasks.py
  plantseg/viewer_napari/widgets/dataprocessing.py
  plantseg/viewer_napari/widgets/utils.py
  tests/conftest.py
  tests/functionals/dataprocessing/test_advanced.py
  tests/tasks/dataprocessing/test_advanced_dataprocessing_tasks.py
  tests/widgets/test_widget_nuc_fix.py
Labels: bug, GUI

#376 Fix Napari relared tests fails
  tests/widgets/test_widget_nuc_fix.py
  tests/widgets/test_widget_open_file.py
  tests/widgets/test_widget_preprocessing.py
Labels: bug, GUI

#384 Fix and test advanced prediction with 2D UNet
  plantseg/viewer_napari/widgets/prediction.py
  tests/widgets/test_widget_pred.py
Labels: bug, GUI

#386 Avoid BioImage.IO Core downloading everything from model zoo entries
  plantseg/functionals/prediction/prediction.py
Labels: enhancement

#387 docs(proofreading): add simple tutorial for proofreading widget
  docs/chapters/plantseg_interactive_napari/proofreading_manual.md
Labels: documentation
