Repository kreshuklab/plant-seg, pull requests merged in 2025-05, with the labels that each got.

#425 build: lift `xarray` and `pydantic` restrictions
  conda-recipe/meta.yaml
  environment-dev-apple.yaml
  environment-dev.yaml
  environment.yaml
Labels: bug

#435 feat: show changelog on welcome screen
  plantseg/tasks/io_tasks.py
  plantseg/utils.py
  plantseg/viewer_napari/viewer.py
  tests/utils/test_utils.py
Labels: enhancement, GUI

#437 fix: napari dock properly behaving
  plantseg/utils.py
  plantseg/viewer_napari/viewer.py
Labels: bug, GUI
